/// English translations
final Map<String, String> enUS = {
  // Common & General
  'app_name': 'My App',
  'loading': 'Loading...',
  'error_title': 'Error',
  'success_title': 'Success',
  'retry': 'Retry',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'save': 'Save',
  'delete': 'Delete',
  'search': 'Search...',
  'refresh': 'Refresh',

  // Authentication
  'login': 'Login',
  'login_subtitle': 'Sign in to continue to your dashboard',
  'username': 'Username',
  'password': 'Password',
  'username_required': 'Username is required',
  'password_required': 'Password is required',
  'login_button': 'Sign In',
  'logging_in': 'Signing in...',
  'login_success': 'Welcome back!',
  'quick_fill': 'Fill Demo Account',
  'logout': 'Logout',
  'logout_confirm': 'Are you sure you want to log out?',

  // Navigation
  'nav_home': 'Home',
  'nav_todos': 'Todos',
  'nav_products': 'Products',
  'nav_settings': 'Settings',

  // Todo Module
  'todos_title': 'Todo List',
  'add_todo': 'Add Todo',
  'new_todo_hint': 'What needs to be done?',
  'filter_all': 'All',
  'filter_pending': 'Pending',
  'filter_completed': 'Completed',
  'no_todos_found': 'No todos found',
  'todo_added': 'Todo added successfully',
  'todo_deleted': 'Todo deleted',
  'todo_updated': 'Todo status updated',
  'delete_todo_confirm': 'Delete this task?',

  // Product Module
  'products_title': 'Product Catalog',
  'search_product_hint': 'Search by product name...',
  'no_products_found': 'No products matching your search',
  'in_stock': 'In Stock',
  'out_of_stock': 'Out of Stock',
  'rating': 'Rating',
  'price': 'Price',
  'discount': 'OFF',

  // Settings
  'language': 'Language',
  'theme': 'Theme',
  'theme_system': 'System',
  'theme_light': 'Light',
  'theme_dark': 'Dark',

  // Diagnostics Module
  'diagnostics_title': 'Device Diagnostics',
  'function_check_title': 'Hardware & Function Check',
  'start_function_check': 'Start Diagnostics',
  'hardware_specs_overview': 'Hardware Specs Overview',
  'hardware_evaluation': 'Standard Evaluation Results',
  'recheck_specs': 'Re-run Tests',

  // Checklist & Requirements
  'pre_check_title': 'Pre-Check Requirements',
  'pre_check_subtitle': 'To ensure test accuracy, please ensure the following features are ready:',
  'req_wifi': 'Turn on Wi-Fi and connect to an Internet network',
  'req_bluetooth': 'Turn on Bluetooth to scan for nearby devices',
  'req_gps': 'Turn on device Location Services (GPS)',
  'req_vibration': 'Hold the device in hand to feel vibration pulses',
  'req_permission': 'Ready to tap "Allow" when prompted for location & Bluetooth permissions',
  'start_diagnostics_now': 'Start Diagnostics',
  'recheck_all': 'Re-run All Tests',
  'testing_in_progress': 'Testing: @step...',

  // 6 Diagnostic Tests
  'ram_test': 'RAM Memory',
  'rom_test': 'Internal Storage (ROM)',
  'ios_sandbox_rom': 'Direct access restricted (iOS Security Sandbox)',
  'wifi_test': 'Wi-Fi Connection',
  'wifi_desc_connected': 'Connected: @ssid',
  'wifi_desc_disconnected': 'Wi-Fi is enabled but not connected to network',
  'wifi_desc_disabled': 'Wi-Fi is currently disabled',
  'bluetooth_test': 'Bluetooth Adapter & Scan',
  'bluetooth_desc_scanned': 'Active • Discovered @count nearby devices',
  'bluetooth_desc_disabled': 'Bluetooth is currently disabled',
  'bluetooth_desc_no_perm': 'Bluetooth scan permission missing',
  'gps_test': 'GPS Location',
  'gps_desc_disabled': 'Location service (GPS) is turned off',
  'gps_desc_no_accuracy': 'Location permission missing or acquiring signal...',
  'gps_desc_accuracy': 'Active • Accuracy radius: ±@accuracym',
  'vibrate_test': 'Vibration Motor',
  'vibrate_desc_unsupported': 'Vibration motor not detected',
  'vibrate_desc_pass': 'Vibration motor verified by user',
  'vibrate_desc_fail': 'Vibration count verification failed',
  'vibrate_dialog_title': 'Vibration Test',
  'vibrate_dialog_content': 'How many times did the phone vibrate?',
  'vibrate_no_vibration': 'Did not vibrate',
  'vibrate_count_times': '@count times',
};

