/// English translations
final Map<String, String> enUS = {
  // Common & General
  'app_name': 'My App',
  'loading': 'Loading...',
  'error_title': 'Error',
  'success_title': 'Success',
  'retry': 'Retry',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'save': 'Save',
  'delete': 'Delete',
  'search': 'Search...',
  'refresh': 'Refresh',

  // Authentication
  'login': 'Login',
  'login_subtitle': 'Sign in to continue to your dashboard',
  'username': 'Username',
  'password': 'Password',
  'username_required': 'Username is required',
  'password_required': 'Password is required',
  'login_button': 'Sign In',
  'logging_in': 'Signing in...',
  'login_success': 'Welcome back!',
  'quick_fill': 'Fill Demo Account',
  'logout': 'Logout',
  'logout_confirm': 'Are you sure you want to log out?',

  // Navigation
  'nav_home': 'Home',
  'nav_todos': 'Todos',
  'nav_products': 'Products',
  'nav_settings': 'Settings',

  // Todo Module
  'todos_title': 'Todo List',
  'add_todo': 'Add Todo',
  'new_todo_hint': 'What needs to be done?',
  'filter_all': 'All',
  'filter_pending': 'Pending',
  'filter_completed': 'Completed',
  'no_todos_found': 'No todos found',
  'todo_added': 'Todo added successfully',
  'todo_deleted': 'Todo deleted',
  'todo_updated': 'Todo status updated',
  'delete_todo_confirm': 'Delete this task?',

  // Product Module
  'products_title': 'Product Catalog',
  'search_product_hint': 'Search by product name...',
  'no_products_found': 'No products matching your search',
  'in_stock': 'In Stock',
  'out_of_stock': 'Out of Stock',
  'rating': 'Rating',
  'price': 'Price',
  'discount': 'OFF',

  // Settings
  'language': 'Language',
  'theme': 'Theme',
  'theme_system': 'System',
  'theme_light': 'Light',
  'theme_dark': 'Dark',

  // Diagnostics Module
  'diagnostics_title': 'Device Diagnostics',
  'function_check_title': 'Hardware & Function Check',
  'start_function_check': 'Start Diagnostics',
  'hardware_specs_overview': 'Hardware Specs Overview',
  'hardware_evaluation': 'Standard Evaluation Results',
  'recheck_specs': 'Re-run Tests',

  // Checklist & Requirements
  'pre_check_title': 'Pre-Check Requirements',
  'pre_check_subtitle': 'To ensure test accuracy, please ensure the following features are ready:',
  'req_wifi': 'Turn on Wi-Fi and connect to an Internet network',
  'req_bluetooth': 'Turn on Bluetooth to scan for nearby devices',
  'req_gps': 'Turn on device Location Services (GPS)',
  'req_vibration': 'Hold the device in hand to feel vibration pulses',
  'req_biometric': 'PIN / Fingerprint / Face ID enrolled in Settings (if device supports it)',
  'req_microphone': 'Ready to tap "Allow" when prompted for Microphone and speak into device',
  'req_permission': 'Ready to tap "Allow" when prompted for location & Bluetooth permissions',
  'start_diagnostics_now': 'Start Diagnostics',
  'recheck_all': 'Re-run All Tests',
  'testing_in_progress': 'Testing: @step...',

  // 6 Diagnostic Tests
  'ram_test': 'RAM Memory',
  'rom_test': 'Internal Storage (ROM)',
  'ios_sandbox_rom': 'Direct access restricted (iOS Security Sandbox)',
  'wifi_test': 'Wi-Fi Connection',
  'wifi_desc_connected': 'Connected: @ssid',
  'wifi_desc_disconnected': 'Wi-Fi is enabled but not connected to network',
  'wifi_desc_disabled': 'Wi-Fi is currently disabled',
  'bluetooth_test': 'Bluetooth Adapter & Scan',
  'bluetooth_desc_scanned': 'Active • Discovered @count nearby devices',
  'bluetooth_desc_disabled': 'Bluetooth is currently disabled',
  'bluetooth_desc_no_perm': 'Bluetooth scan permission missing',
  'gps_test': 'GPS Location',
  'gps_desc_disabled': 'Location service (GPS) is turned off',
  'gps_desc_no_accuracy': 'Location permission missing or acquiring signal...',
  'gps_desc_accuracy': 'Active • Accuracy radius: ±@accuracym',
  'vibrate_test': 'Vibration Motor',
  'vibrate_desc_unsupported': 'Vibration motor not detected',
  'vibrate_desc_pass': 'Vibration motor verified by user',
  'vibrate_desc_fail': 'Vibration count verification failed',
  'vibrate_dialog_title': 'Vibration Test',
  'vibrate_dialog_content': 'How many times did the phone vibrate?',
  'vibrate_no_vibration': 'Did not vibrate',
  'vibrate_count_times': '@count times',

  // Biometric Test
  'biometric_test': 'Biometric Sensor',
  'bio_desc_available': 'Available • Sensor ready and security enrolled',
  'bio_desc_not_enrolled': 'Hardware supported • No biometric/PIN enrolled in Settings',
  'bio_desc_unsupported': 'Biometric hardware not supported on this device',
  'bio_desc_failed': 'Biometric sensor hardware failure',
  'bio_chip_label': 'Biometric Sensor',
  'bio_chip_available': 'Available',
  'bio_chip_unavailable': 'Not Available',

  // Microphone Test
  'mic_test': 'Microphone & Audio',
  'mic_desc_pass': 'Working properly • Recorded & played back clearly',
  'mic_desc_fail': 'Audio distorted, faint, or speech not detected',
  'mic_desc_no_perm': 'Microphone permission missing',
  'mic_test_dialog_title': 'Microphone Test',
  'mic_speak_prompt': 'Please speak into the phone microphone...',
  'mic_playing_prompt': 'Playing back the recorded audio...',
  'mic_confirm_prompt': 'Confirm audio quality',
  'mic_countdown': 'Recording: @seconds s...',
  'mic_playing_audio': 'Playing back audio...',
  'mic_confirm_hint': 'Recording & playback completed',
  'mic_listen_carefully': 'Listen to hear if playback from speaker is clear',
  'mic_ask_hear': 'Did you hear the playback clearly?',
  'mic_hear_clearly': 'Heard Clearly',
  'mic_cannot_hear': 'Cannot Hear',
  'mic_permission_denied': 'Microphone permission was denied by the OS.',
  'mic_hardware_permission_denied': 'Audio recording hardware not available or denied.',

  // Keys Test (Physical Keys)
  'req_keys': 'Be ready to press Volume (+ / -) hardware keys when prompted',
  'keys_test': 'Physical Keys (Volume & Power)',
  'keys_test_title': 'Physical Keys Test',
  'keys_test_subtitle': 'Test responsiveness of Volume Up/Down, Power, and Back buttons',
  'keys_desc_pass': 'Working properly • Both Vol+ and Vol- keys detected',
  'keys_desc_fail': 'Key detection incomplete or unresponsive buttons',
  'keys_desc_pending': 'Physical keys not tested yet',
  'keys_vol_up': 'Volume Up (Vol +)',
  'keys_vol_down': 'Volume Down (Vol -)',
  'keys_power': 'Power Button',
  'keys_back': 'Back Button',
  'keys_status_pressed': 'Key Detected',
  'keys_status_waiting': 'Waiting for press...',
  'keys_mode_free': 'Free Mode',
  'keys_mode_sequential': 'Auto Vol+/-',
  'keys_prompt_press_vol_up': 'Press Volume Up key once (+)',
  'keys_prompt_press_vol_down': 'Press Volume Down key once (-)',
  'keys_prompt_free': 'Press Vol+ and Vol- keys at any time',
  'keys_prompt_completed': 'Both keys detected successfully!',
  'keys_manual_hint': 'On iOS or fallback scenarios, you can tap directly on the tile to confirm manually.',
  'keys_countdown_seconds': 'Timeout: @seconds seconds',
  'keys_finish_test': 'Finish Test',
  'keys_reset_test': 'Reset Test',
  'keys_auto_next_step': 'Automatically advances upon detection',

  // Camera Test (Front & Rear Camera)
  'req_camera': 'Be ready to grant Camera permission and take comparison photos',
  'camera_test': 'Camera (Front & Rear)',
  'camera_test_title': 'Camera Diagnostics',
  'camera_test_subtitle': 'Check sharpness, sensor integrity, Flash, and comparison match',
  'camera_desc_pass': 'Working properly • Sharp photos & sensor verified',
  'camera_desc_fail': 'Image mismatch, black/distorted or sensor error',
  'camera_desc_pending': 'Camera not tested yet',
  'camera_desc_no_perm': 'Camera permission not granted',
  'camera_step_back_preview': 'Rear Cam',
  'camera_step_back_compare': 'Rear Match',
  'camera_step_front_preview': 'Front Cam',
  'camera_step_front_compare': 'Front Match',
  'camera_step_finish': 'Completed',
  'camera_prompt_back': 'Point rear camera at a clear object and tap Capture',
  'camera_prompt_front': 'Point front camera at your face and tap Capture',
  'camera_take_photo': 'Take Photo',
  'camera_retake': 'Retake',
  'camera_compare_title': 'Compare Capture with Real View',
  'camera_compare_subtitle': 'Verify whether the photo is clear, not black, striped, or corrupted',
  'camera_live_preview': 'Live Viewfinder',
  'camera_captured_image': 'Captured Photo',
  'camera_confirm_match': 'Sharp & Matches Real View',
  'camera_confirm_mismatch': 'Photo Error / Sensor Broken',
  'camera_flash_toggle': 'Flash',
  'camera_flash_on': 'Flash On',
  'camera_flash_off': 'Flash Off',
  'camera_no_cameras_found': 'No camera hardware found on this device.',
  'camera_permission_denied': 'Camera permission is required for diagnostics.',
  'camera_summary_all_good': 'Both front and rear cameras operate perfectly!',
};

