/// Vietnamese translations
final Map<String, String> viVN = {
  // Common & General
  'app_name': 'My App',
  'loading': 'Đang tải...',
  'error_title': 'Đã xảy ra lỗi',
  'success_title': 'Thành công',
  'retry': 'Thử lại',
  'cancel': 'Hủy',
  'confirm': 'Xác nhận',
  'save': 'Lưu',
  'delete': 'Xóa',
  'search': 'Tìm kiếm...',
  'refresh': 'Làm mới',

  // Authentication
  'login': 'Đăng nhập',
  'login_subtitle': 'Đăng nhập để tiếp tục vào ứng dụng',
  'username': 'Tên đăng nhập',
  'password': 'Mật khẩu',
  'username_required': 'Vui lòng nhập tên đăng nhập',
  'password_required': 'Vui lòng nhập mật khẩu',
  'login_button': 'Đăng nhập ngay',
  'logging_in': 'Đang đăng nhập...',
  'login_success': 'Đăng nhập thành công!',
  'quick_fill': 'Điền tài khoản mẫu',
  'logout': 'Đăng xuất',
  'logout_confirm': 'Bạn có chắc chắn muốn đăng xuất?',

  // Navigation
  'nav_home': 'Trang chủ',
  'nav_todos': 'Công việc',
  'nav_products': 'Sản phẩm',
  'nav_settings': 'Cài đặt',

  // Todo Module
  'todos_title': 'Danh sách công việc',
  'add_todo': 'Thêm công việc',
  'new_todo_hint': 'Bạn cần làm việc gì tiếp theo?',
  'filter_all': 'Tất cả',
  'filter_pending': 'Đang chờ',
  'filter_completed': 'Đã xong',
  'no_todos_found': 'Không có công việc nào',
  'todo_added': 'Thêm công việc thành công',
  'todo_deleted': 'Đã xóa công việc',
  'todo_updated': 'Đã cập nhật trạng thái',
  'delete_todo_confirm': 'Bạn muốn xóa công việc này?',

  // Product Module
  'products_title': 'Danh mục sản phẩm',
  'search_product_hint': 'Tìm kiếm tên sản phẩm...',
  'no_products_found': 'Không tìm thấy sản phẩm nào',
  'in_stock': 'Còn hàng',
  'out_of_stock': 'Hết hàng',
  'rating': 'Đánh giá',
  'price': 'Giá',
  'discount': 'GIẢM',

  // Settings
  'language': 'Ngôn ngữ',
  'theme': 'Giao diện',
  'theme_system': 'Hệ thống',
  'theme_light': 'Sáng',
  'theme_dark': 'Tối',

  // Diagnostics Module
  'diagnostics_title': 'Kiểm định thiết bị',
  'function_check_title': 'Kiểm tra phần cứng & chức năng',
  'start_function_check': 'Bắt đầu kiểm tra',
  'hardware_specs_overview': 'Tổng quan thông số phần cứng',
  'hardware_evaluation': 'Kết quả đánh giá tiêu chuẩn',
  'recheck_specs': 'Kiểm tra lại',

  // Checklist & Requirements
  'pre_check_title': 'Yêu cầu chuẩn bị trước khi kiểm tra',
  'pre_check_subtitle': 'Để quá trình đo đạc đạt kết quả chính xác, vui lòng đảm bảo thiết bị đã sẵn sàng:',
  'req_wifi': 'Bật Wi-Fi và kết nối vào một mạng Internet',
  'req_bluetooth': 'Bật Bluetooth để quét tìm thiết bị xung quanh',
  'req_gps': 'Bật dịch vụ định vị GPS của thiết bị',
  'req_vibration': 'Cầm chắc máy trên tay để cảm nhận số lần rung',
  'req_permission': 'Sẵn sàng bấm "Cho phép" khi hệ thống xin quyền vị trí & Bluetooth',
  'start_diagnostics_now': 'Bắt đầu kiểm tra',
  'recheck_all': 'Kiểm tra lại toàn bộ',
  'testing_in_progress': 'Đang kiểm tra: @step...',

  // 6 Diagnostic Tests
  'ram_test': 'Bộ nhớ RAM',
  'rom_test': 'Bộ nhớ trong (ROM)',
  'ios_sandbox_rom': 'Miễn đọc trực tiếp (Sandbox bảo mật iOS)',
  'wifi_test': 'Kết nối Wi-Fi',
  'wifi_desc_connected': 'Đã kết nối: @ssid',
  'wifi_desc_disconnected': 'Wi-Fi đang bật nhưng chưa kết nối mạng',
  'wifi_desc_disabled': 'Wi-Fi hiện đang tắt',
  'bluetooth_test': 'Kiểm tra Bluetooth & Quét thiết bị',
  'bluetooth_desc_scanned': 'Hoạt động tốt • Đã quét thấy @count thiết bị xung quanh',
  'bluetooth_desc_disabled': 'Bluetooth hiện đang tắt',
  'bluetooth_desc_no_perm': 'Chưa được cấp quyền quét Bluetooth',
  'gps_test': 'Định vị GPS',
  'gps_desc_disabled': 'Dịch vụ định vị GPS hiện đang tắt',
  'gps_desc_no_accuracy': 'Chưa cấp quyền vị trí hoặc đang dò tín hiệu...',
  'gps_desc_accuracy': 'Hoạt động tốt • Sai số định vị: ±@accuracym',
  'vibrate_test': 'Chức năng Rung',
  'vibrate_desc_unsupported': 'Thiết bị không hỗ trợ mô-tơ rung',
  'vibrate_desc_pass': 'Phần cứng rung hoạt động tốt (Đã xác nhận)',
  'vibrate_desc_fail': 'Số lần rung không khớp hoặc chưa kiểm tra',
  'vibrate_dialog_title': 'Kiểm tra rung',
  'vibrate_dialog_content': 'Máy vừa rung bao nhiêu lần?',
  'vibrate_no_vibration': 'Không rung',
  'vibrate_count_times': '@count lần',
};

