/// Vietnamese translations
final Map<String, String> viVN = {
  // Common & General
  'app_name': 'My App',
  'loading': 'Đang tải...',
  'error_title': 'Đã xảy ra lỗi',
  'success_title': 'Thành công',
  'retry': 'Thử lại',
  'cancel': 'Hủy',
  'confirm': 'Xác nhận',
  'save': 'Lưu',
  'delete': 'Xóa',
  'search': 'Tìm kiếm...',
  'refresh': 'Làm mới',

  // Authentication
  'login': 'Đăng nhập',
  'login_subtitle': 'Đăng nhập để tiếp tục vào ứng dụng',
  'username': 'Tên đăng nhập',
  'password': 'Mật khẩu',
  'username_required': 'Vui lòng nhập tên đăng nhập',
  'password_required': 'Vui lòng nhập mật khẩu',
  'login_button': 'Đăng nhập ngay',
  'logging_in': 'Đang đăng nhập...',
  'login_success': 'Đăng nhập thành công!',
  'quick_fill': 'Điền tài khoản mẫu',
  'logout': 'Đăng xuất',
  'logout_confirm': 'Bạn có chắc chắn muốn đăng xuất?',

  // Navigation
  'nav_home': 'Trang chủ',
  'nav_todos': 'Công việc',
  'nav_products': 'Sản phẩm',
  'nav_settings': 'Cài đặt',

  // Todo Module
  'todos_title': 'Danh sách công việc',
  'add_todo': 'Thêm công việc',
  'new_todo_hint': 'Bạn cần làm việc gì tiếp theo?',
  'filter_all': 'Tất cả',
  'filter_pending': 'Đang chờ',
  'filter_completed': 'Đã xong',
  'no_todos_found': 'Không có công việc nào',
  'todo_added': 'Thêm công việc thành công',
  'todo_deleted': 'Đã xóa công việc',
  'todo_updated': 'Đã cập nhật trạng thái',
  'delete_todo_confirm': 'Bạn muốn xóa công việc này?',

  // Product Module
  'products_title': 'Danh mục sản phẩm',
  'search_product_hint': 'Tìm kiếm tên sản phẩm...',
  'no_products_found': 'Không tìm thấy sản phẩm nào',
  'in_stock': 'Còn hàng',
  'out_of_stock': 'Hết hàng',
  'rating': 'Đánh giá',
  'price': 'Giá',
  'discount': 'GIẢM',

  // Settings
  'language': 'Ngôn ngữ',
  'theme': 'Giao diện',
  'theme_system': 'Hệ thống',
  'theme_light': 'Sáng',
  'theme_dark': 'Tối',

  // Diagnostics Module
  'diagnostics_title': 'Kiểm định thiết bị',
  'function_check_title': 'Kiểm tra phần cứng & chức năng',
  'start_function_check': 'Bắt đầu kiểm tra',
  'hardware_specs_overview': 'Tổng quan thông số phần cứng',
  'hardware_evaluation': 'Kết quả đánh giá tiêu chuẩn',
  'recheck_specs': 'Kiểm tra lại',

  // Checklist & Requirements
  'pre_check_title': 'Yêu cầu chuẩn bị trước khi kiểm tra',
  'pre_check_subtitle': 'Để quá trình đo đạc đạt kết quả chính xác, vui lòng đảm bảo thiết bị đã sẵn sàng:',
  'req_wifi': 'Bật Wi-Fi và kết nối vào một mạng Internet',
  'req_bluetooth': 'Bật Bluetooth để quét tìm thiết bị xung quanh',
  'req_gps': 'Bật dịch vụ định vị GPS của thiết bị',
  'req_vibration': 'Cầm chắc máy trên tay để cảm nhận số lần rung',
  'req_biometric': 'Thiết bị đã cài đặt mã PIN / Vân tay / Khuôn mặt (nếu máy có hỗ trợ)',
  'req_microphone': 'Sẵn sàng bấm "Cho phép" khi hệ thống xin quyền Micro và nói vào máy',
  'req_permission': 'Sẵn sàng bấm "Cho phép" khi hệ thống xin quyền vị trí & Bluetooth',
  'start_diagnostics_now': 'Bắt đầu kiểm tra',
  'recheck_all': 'Kiểm tra lại toàn bộ',
  'testing_in_progress': 'Đang kiểm tra: @step...',

  // 6 Diagnostic Tests
  'ram_test': 'Bộ nhớ RAM',
  'rom_test': 'Bộ nhớ trong (ROM)',
  'ios_sandbox_rom': 'Miễn đọc trực tiếp (Sandbox bảo mật iOS)',
  'wifi_test': 'Kết nối Wi-Fi',
  'wifi_desc_connected': 'Đã kết nối: @ssid',
  'wifi_desc_disconnected': 'Wi-Fi đang bật nhưng chưa kết nối mạng',
  'wifi_desc_disabled': 'Wi-Fi hiện đang tắt',
  'bluetooth_test': 'Kiểm tra Bluetooth & Quét thiết bị',
  'bluetooth_desc_scanned': 'Hoạt động tốt • Đã quét thấy @count thiết bị xung quanh',
  'bluetooth_desc_disabled': 'Bluetooth hiện đang tắt',
  'bluetooth_desc_no_perm': 'Chưa được cấp quyền quét Bluetooth',
  'gps_test': 'Định vị GPS',
  'gps_desc_disabled': 'Dịch vụ định vị GPS hiện đang tắt',
  'gps_desc_no_accuracy': 'Chưa cấp quyền vị trí hoặc đang dò tín hiệu...',
  'gps_desc_accuracy': 'Hoạt động tốt • Sai số định vị: ±@accuracym',
  'vibrate_test': 'Chức năng Rung',
  'vibrate_desc_unsupported': 'Thiết bị không hỗ trợ mô-tơ rung',
  'vibrate_desc_pass': 'Phần cứng rung hoạt động tốt (Đã xác nhận)',
  'vibrate_desc_fail': 'Số lần rung không khớp hoặc chưa kiểm tra',
  'vibrate_dialog_title': 'Kiểm tra rung',
  'vibrate_dialog_content': 'Máy vừa rung bao nhiêu lần?',
  'vibrate_no_vibration': 'Không rung',
  'vibrate_count_times': '@count lần',

  // Biometric Test
  'biometric_test': 'Cảm biến Sinh trắc học',
  'bio_desc_available': 'Khả dụng • Cảm biến sẵn sàng và đã thiết lập',
  'bio_desc_not_enrolled': 'Hỗ trợ phần cứng • Chưa cài đặt vân tay/khuôn mặt',
  'bio_desc_unsupported': 'Thiết bị không hỗ trợ công nghệ sinh trắc học',
  'bio_desc_failed': 'Lỗi cảm biến sinh trắc học phần cứng',
  'bio_chip_label': 'Cảm biến sinh trắc',
  'bio_chip_available': 'Khả dụng',
  'bio_chip_unavailable': 'Không hỗ trợ',

  // Microphone Test
  'mic_test': 'Microphone & Thu âm',
  'mic_desc_pass': 'Hoạt động tốt • Đã thu và phát lại rõ ràng',
  'mic_desc_fail': 'Âm thanh không rõ hoặc không nhận được tiếng nói',
  'mic_desc_no_perm': 'Chưa được cấp quyền Microphone',
  'mic_test_dialog_title': 'Kiểm tra Microphone',
  'mic_speak_prompt': 'Vui lòng nói một câu vào micro của máy...',
  'mic_playing_prompt': 'Đang phát lại đoạn âm thanh vừa thu...',
  'mic_confirm_prompt': 'Xác nhận chất lượng âm thanh',
  'mic_countdown': 'Đang thu âm: @seconds giây...',
  'mic_playing_audio': 'Đang phát lại âm thanh...',
  'mic_confirm_hint': 'Đã hoàn tất thu & phát âm thanh',
  'mic_listen_carefully': 'Lắng nghe xem âm thanh phát ra từ loa có rõ ràng không',
  'mic_ask_hear': 'Bạn có nghe thấy âm thanh vừa phát lại không?',
  'mic_hear_clearly': 'Nghe rõ',
  'mic_cannot_hear': 'Không nghe thấy',
  'mic_permission_denied': 'Ứng dụng không có quyền Microphone từ hệ điều hành.',
  'mic_hardware_permission_denied': 'Phần cứng ghi âm không sẵn sàng hoặc bị từ chối.',

  // Keys Test (Phím vật lý)
  'req_keys': 'Sẵn sàng bấm các phím cứng Âm lượng (+ / -) khi được yêu cầu',
  'keys_test': 'Phím vật lý (Âm lượng & Nguồn)',
  'keys_test_title': 'Kiểm tra Phím vật lý',
  'keys_test_subtitle': 'Kiểm tra độ phản hồi của nút Tăng/Giảm âm lượng, Nguồn và Quay lại',
  'keys_desc_pass': 'Hoạt động tốt • Đã nhận diện đầy đủ phím Vol+ và Vol-',
  'keys_desc_fail': 'Chưa nhận diện đủ phím hoặc nút bị liệt',
  'keys_desc_pending': 'Chưa kiểm tra phím vật lý',
  'keys_vol_up': 'Tăng âm lượng (Vol +)',
  'keys_vol_down': 'Giảm âm lượng (Vol -)',
  'keys_power': 'Phím Nguồn (Power)',
  'keys_back': 'Phím Quay lại (Back)',
  'keys_status_pressed': 'Đã nhận phím',
  'keys_status_waiting': 'Chờ bấm...',
  'keys_mode_free': 'Chế độ Tự do',
  'keys_mode_sequential': 'Tự động Vol+/-',
  'keys_prompt_press_vol_up': 'Nhấn 1 lần phím Tăng âm lượng (+)',
  'keys_prompt_press_vol_down': 'Nhấn 1 lần phím Giảm âm lượng (-)',
  'keys_prompt_free': 'Bấm phím Vol+ và Vol- bất kỳ lúc nào',
  'keys_prompt_completed': 'Đã nhận diện thành công cả 2 phím!',
  'keys_manual_hint': 'Trên iOS hoặc trường hợp đặc biệt, bạn có thể chạm trực tiếp vào ô để xác nhận thủ công.',
  'keys_countdown_seconds': 'Thời gian chờ: @seconds giây',
  'keys_finish_test': 'Hoàn tất kiểm tra',
  'keys_reset_test': 'Kiểm tra lại',
  'keys_auto_next_step': 'Tự động chuyển bước sau khi nhận diện',

  // Camera Test (Camera trước & sau)
  'req_camera': 'Sẵn sàng cấp quyền Camera và chụp ảnh đối chiếu trước / sau',
  'camera_test': 'Camera (Trước & Sau)',
  'camera_test_title': 'Kiểm tra Camera',
  'camera_test_subtitle': 'Kiểm tra độ nét, cảm biến, đèn Flash và đối chiếu hình chụp',
  'camera_desc_pass': 'Hoạt động tốt • Ảnh chụp rõ nét & khớp cảm biến',
  'camera_desc_fail': 'Ảnh không khớp, bị mờ/đen hoặc cảm biến lỗi',
  'camera_desc_pending': 'Chưa kiểm tra camera',
  'camera_desc_no_perm': 'Chưa được cấp quyền Camera',
  'camera_step_back_preview': 'Cam sau',
  'camera_step_back_compare': 'So khớp sau',
  'camera_step_front_preview': 'Cam trước',
  'camera_step_front_compare': 'So khớp trước',
  'camera_step_finish': 'Hoàn tất',
  'camera_prompt_back': 'Hướng camera sau vào vật thể rõ ràng rồi nhấn nút Chụp',
  'camera_prompt_front': 'Hướng camera trước vào khuôn mặt bạn rồi nhấn nút Chụp',
  'camera_take_photo': 'Chụp ảnh',
  'camera_retake': 'Chụp lại',
  'camera_compare_title': 'So khớp hình chụp với thực tế',
  'camera_compare_subtitle': 'Kiểm tra xem ảnh chụp có bị đen xì, sọc, mờ hoặc biến dạng không',
  'camera_live_preview': 'Khung ngắm trực tiếp',
  'camera_captured_image': 'Hình ảnh vừa chụp',
  'camera_confirm_match': 'Ảnh rõ nét & Khớp thực tế',
  'camera_confirm_mismatch': 'Ảnh lỗi / Hỏng cảm biến',
  'camera_flash_toggle': 'Đèn Flash',
  'camera_flash_on': 'Bật Flash',
  'camera_flash_off': 'Tắt Flash',
  'camera_no_cameras_found': 'Không tìm thấy phần cứng camera trên thiết bị.',
  'camera_permission_denied': 'Ứng dụng cần quyền Camera để thẩm định máy.',
  'camera_summary_all_good': 'Cả 2 camera trước và sau hoạt động hoàn hảo!',
};

